### ISSUE TITLE
No issue, but suggestions

### ISSUE THREAD

**Issue by M1Aston** [isometimesgit/MediaExtractor#1]
This add-on works pretty well, Very useful for my not so recent, less powerful pc. however, having it enabled all the time can cause problems, so I simply enable it when needed. My thought:

- Could we have a different icon (colour) for enabled and disabled? Mistakes less likely.
- An easier, faster way enable\disable (for example a simple right click) instead of having to use the menu?

**Comment by isometimesgit** [comment]
I have changed the default icon to green when enabled in version 1.2.0
I dont think there is a faster way to enable / disable without losing the popup menu. 
I use the whitelist feature more than enabling / disabling depends how you use it I guess.

**Comment by M1Aston** [comment]
That's great. Very helpful. Thank you very much for that. Also for your quick response.
